[Wyscout V3] Add position information for players
PySport/kloppy pull request #366
Opened 2024-11-21 17:49 UTC by DriesDeprest

2024-12-02 21:04 UTC, probberechts requested changes

2024-12-02 21:06 UTC, probberechts commented on kloppy/infra/serializers/event/wyscout/deserializer_v3.py
> +    starting_formation = formations[formation_str]
```suggestion
    starting_formation = formations.get(formation_str)
```

2024-12-02 21:07 UTC, probberechts commented on kloppy/infra/serializers/event/wyscout/deserializer_v3.py
> +        player_id: position_types_mapping[player_info["position"].upper()]
```suggestion
        player_id: position_types_mapping.get(player_info["position"].upper(), PositionType.Unknown)
```

2024-12-03 10:28 UTC, DriesDeprest commented
Thanks for the input @probberechts, I've resolved the change requests.

2024-12-03 17:50 UTC, probberechts approved these changes

2024-12-03 17:53 UTC, merged